// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/voting/v1/voting.proto

package votingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SubmitRequest carries the TRC update a core seeking voting power signed
// with its regular voting key — the proof of possession over the certificate
// the successor carries — for the core's control plane to decide on.
type SubmitRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// trc is the DER-encoded CMS-signed TRC, partially signed: the submitter's
	// signer info over the assembled successor, the founder's vote still
	// missing.
	Trc           []byte `protobuf:"bytes,1,opt,name=trc,proto3" json:"trc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitRequest) Reset() {
	*x = SubmitRequest{}
	mi := &file_proto_voting_v1_voting_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitRequest) ProtoMessage() {}

func (x *SubmitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_voting_v1_voting_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitRequest.ProtoReflect.Descriptor instead.
func (*SubmitRequest) Descriptor() ([]byte, []int) {
	return file_proto_voting_v1_voting_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitRequest) GetTrc() []byte {
	if x != nil {
		return x.Trc
	}
	return nil
}

// SubmitResponse answers with the completed TRC: the submitted successor
// carrying the founder's sensitive vote beside the submitter's proof of
// possession, verified and pinned — or, when the newest TRC already names
// the submitter, that TRC as pinned.
type SubmitResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// trc is the DER-encoded CMS-signed TRC.
	Trc           []byte `protobuf:"bytes,1,opt,name=trc,proto3" json:"trc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitResponse) Reset() {
	*x = SubmitResponse{}
	mi := &file_proto_voting_v1_voting_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitResponse) ProtoMessage() {}

func (x *SubmitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_voting_v1_voting_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitResponse.ProtoReflect.Descriptor instead.
func (*SubmitResponse) Descriptor() ([]byte, []int) {
	return file_proto_voting_v1_voting_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitResponse) GetTrc() []byte {
	if x != nil {
		return x.Trc
	}
	return nil
}

var File_proto_voting_v1_voting_proto protoreflect.FileDescriptor

const file_proto_voting_v1_voting_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/voting/v1/voting.proto\x12\tvoting.v1\"!\n" +
	"\rSubmitRequest\x12\x10\n" +
	"\x03trc\x18\x01 \x01(\fR\x03trc\"\"\n" +
	"\x0eSubmitResponse\x12\x10\n" +
	"\x03trc\x18\x01 \x01(\fR\x03trc2N\n" +
	"\rVotingService\x12=\n" +
	"\x06Submit\x12\x18.voting.v1.SubmitRequest\x1a\x19.voting.v1.SubmitResponseB2Z0github.com/fancl20/cion/proto/voting/v1;votingv1b\x06proto3"

var (
	file_proto_voting_v1_voting_proto_rawDescOnce sync.Once
	file_proto_voting_v1_voting_proto_rawDescData []byte
)

func file_proto_voting_v1_voting_proto_rawDescGZIP() []byte {
	file_proto_voting_v1_voting_proto_rawDescOnce.Do(func() {
		file_proto_voting_v1_voting_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_voting_v1_voting_proto_rawDesc), len(file_proto_voting_v1_voting_proto_rawDesc)))
	})
	return file_proto_voting_v1_voting_proto_rawDescData
}

var file_proto_voting_v1_voting_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_voting_v1_voting_proto_goTypes = []any{
	(*SubmitRequest)(nil),  // 0: voting.v1.SubmitRequest
	(*SubmitResponse)(nil), // 1: voting.v1.SubmitResponse
}
var file_proto_voting_v1_voting_proto_depIdxs = []int32{
	0, // 0: voting.v1.VotingService.Submit:input_type -> voting.v1.SubmitRequest
	1, // 1: voting.v1.VotingService.Submit:output_type -> voting.v1.SubmitResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_voting_v1_voting_proto_init() }
func file_proto_voting_v1_voting_proto_init() {
	if File_proto_voting_v1_voting_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_voting_v1_voting_proto_rawDesc), len(file_proto_voting_v1_voting_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_voting_v1_voting_proto_goTypes,
		DependencyIndexes: file_proto_voting_v1_voting_proto_depIdxs,
		MessageInfos:      file_proto_voting_v1_voting_proto_msgTypes,
	}.Build()
	File_proto_voting_v1_voting_proto = out.File
	file_proto_voting_v1_voting_proto_goTypes = nil
	file_proto_voting_v1_voting_proto_depIdxs = nil
}
