// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/node/v1/directory.proto

package nodev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Entry is one node's publication: everything the selection loop needs to
// probe the node as a candidate neighbor.
type Entry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// isd_as is the publisher's ISD-AS. The directory records the ISD-AS the
	// authenticated publisher's certificate names, never the claimed one.
	IsdAs uint64 `protobuf:"varint,1,opt,name=isd_as,json=isdAs,proto3" json:"isd_as,omitempty"`
	// control_addr is the underlay "host:port" address of the publisher's
	// control service; its endpoint and rendezvous ports derive from the host.
	ControlAddr string `protobuf:"bytes,2,opt,name=control_addr,json=controlAddr,proto3" json:"control_addr,omitempty"`
	// rendezvous_addr is the underlay "host:port" address the publisher's
	// rendezvous acceptor listens on for first contact.
	RendezvousAddr string `protobuf:"bytes,3,opt,name=rendezvous_addr,json=rendezvousAddr,proto3" json:"rendezvous_addr,omitempty"`
	// private marks a node behind address translation: joinable by no one,
	// candidate for no one's redundancy floor (ADR-0006's reachability class).
	Private       bool `protobuf:"varint,4,opt,name=private,proto3" json:"private,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_proto_node_v1_directory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_v1_directory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_proto_node_v1_directory_proto_rawDescGZIP(), []int{0}
}

func (x *Entry) GetIsdAs() uint64 {
	if x != nil {
		return x.IsdAs
	}
	return 0
}

func (x *Entry) GetControlAddr() string {
	if x != nil {
		return x.ControlAddr
	}
	return ""
}

func (x *Entry) GetRendezvousAddr() string {
	if x != nil {
		return x.RendezvousAddr
	}
	return ""
}

func (x *Entry) GetPrivate() bool {
	if x != nil {
		return x.Private
	}
	return false
}

type PublishRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// entry is the publisher's claimed entry; the ISD-AS comes from the
	// authenticated certificate chain, the rest from the entry.
	Entry         *Entry `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishRequest) Reset() {
	*x = PublishRequest{}
	mi := &file_proto_node_v1_directory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRequest) ProtoMessage() {}

func (x *PublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_v1_directory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRequest.ProtoReflect.Descriptor instead.
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return file_proto_node_v1_directory_proto_rawDescGZIP(), []int{1}
}

func (x *PublishRequest) GetEntry() *Entry {
	if x != nil {
		return x.Entry
	}
	return nil
}

type PublishResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishResponse) Reset() {
	*x = PublishResponse{}
	mi := &file_proto_node_v1_directory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishResponse) ProtoMessage() {}

func (x *PublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_v1_directory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishResponse.ProtoReflect.Descriptor instead.
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return file_proto_node_v1_directory_proto_rawDescGZIP(), []int{2}
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_proto_node_v1_directory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_v1_directory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_proto_node_v1_directory_proto_rawDescGZIP(), []int{3}
}

type ListResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// entries holds one entry per publishing node.
	Entries       []*Entry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_proto_node_v1_directory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_v1_directory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_proto_node_v1_directory_proto_rawDescGZIP(), []int{4}
}

func (x *ListResponse) GetEntries() []*Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_proto_node_v1_directory_proto protoreflect.FileDescriptor

const file_proto_node_v1_directory_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/node/v1/directory.proto\x12\anode.v1\"\x84\x01\n" +
	"\x05Entry\x12\x15\n" +
	"\x06isd_as\x18\x01 \x01(\x04R\x05isdAs\x12!\n" +
	"\fcontrol_addr\x18\x02 \x01(\tR\vcontrolAddr\x12'\n" +
	"\x0frendezvous_addr\x18\x03 \x01(\tR\x0erendezvousAddr\x12\x18\n" +
	"\aprivate\x18\x04 \x01(\bR\aprivate\"6\n" +
	"\x0ePublishRequest\x12$\n" +
	"\x05entry\x18\x01 \x01(\v2\x0e.node.v1.EntryR\x05entry\"\x11\n" +
	"\x0fPublishResponse\"\r\n" +
	"\vListRequest\"8\n" +
	"\fListResponse\x12(\n" +
	"\aentries\x18\x01 \x03(\v2\x0e.node.v1.EntryR\aentries2\x85\x01\n" +
	"\x10DirectoryService\x12<\n" +
	"\aPublish\x12\x17.node.v1.PublishRequest\x1a\x18.node.v1.PublishResponse\x123\n" +
	"\x04List\x12\x14.node.v1.ListRequest\x1a\x15.node.v1.ListResponseB.Z,github.com/fancl20/cion/proto/node/v1;nodev1b\x06proto3"

var (
	file_proto_node_v1_directory_proto_rawDescOnce sync.Once
	file_proto_node_v1_directory_proto_rawDescData []byte
)

func file_proto_node_v1_directory_proto_rawDescGZIP() []byte {
	file_proto_node_v1_directory_proto_rawDescOnce.Do(func() {
		file_proto_node_v1_directory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_node_v1_directory_proto_rawDesc), len(file_proto_node_v1_directory_proto_rawDesc)))
	})
	return file_proto_node_v1_directory_proto_rawDescData
}

var file_proto_node_v1_directory_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_node_v1_directory_proto_goTypes = []any{
	(*Entry)(nil),           // 0: node.v1.Entry
	(*PublishRequest)(nil),  // 1: node.v1.PublishRequest
	(*PublishResponse)(nil), // 2: node.v1.PublishResponse
	(*ListRequest)(nil),     // 3: node.v1.ListRequest
	(*ListResponse)(nil),    // 4: node.v1.ListResponse
}
var file_proto_node_v1_directory_proto_depIdxs = []int32{
	0, // 0: node.v1.PublishRequest.entry:type_name -> node.v1.Entry
	0, // 1: node.v1.ListResponse.entries:type_name -> node.v1.Entry
	1, // 2: node.v1.DirectoryService.Publish:input_type -> node.v1.PublishRequest
	3, // 3: node.v1.DirectoryService.List:input_type -> node.v1.ListRequest
	2, // 4: node.v1.DirectoryService.Publish:output_type -> node.v1.PublishResponse
	4, // 5: node.v1.DirectoryService.List:output_type -> node.v1.ListResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_node_v1_directory_proto_init() }
func file_proto_node_v1_directory_proto_init() {
	if File_proto_node_v1_directory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_node_v1_directory_proto_rawDesc), len(file_proto_node_v1_directory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_node_v1_directory_proto_goTypes,
		DependencyIndexes: file_proto_node_v1_directory_proto_depIdxs,
		MessageInfos:      file_proto_node_v1_directory_proto_msgTypes,
	}.Build()
	File_proto_node_v1_directory_proto = out.File
	file_proto_node_v1_directory_proto_goTypes = nil
	file_proto_node_v1_directory_proto_depIdxs = nil
}
