// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/node/v1/link.proto

package nodev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LinkRequest asks the peer to admit a direct link between the two nodes,
// riding the control endpoint's authenticated channel (ADR-0008): the
// requester is named by its verified certificate chain, never by a claim.
type LinkRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// local_addr is the requester's link local underlay address, "host:port".
	LocalAddr string `protobuf:"bytes,1,opt,name=local_addr,json=localAddr,proto3" json:"local_addr,omitempty"`
	// if_id is the requester's interface ID of the link.
	IfId          uint32 `protobuf:"varint,2,opt,name=if_id,json=ifId,proto3" json:"if_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkRequest) Reset() {
	*x = LinkRequest{}
	mi := &file_proto_node_v1_link_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkRequest) ProtoMessage() {}

func (x *LinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_v1_link_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkRequest.ProtoReflect.Descriptor instead.
func (*LinkRequest) Descriptor() ([]byte, []int) {
	return file_proto_node_v1_link_proto_rawDescGZIP(), []int{0}
}

func (x *LinkRequest) GetLocalAddr() string {
	if x != nil {
		return x.LocalAddr
	}
	return ""
}

func (x *LinkRequest) GetIfId() uint32 {
	if x != nil {
		return x.IfId
	}
	return 0
}

// LinkReply carries the acceptor's side of the link: the address and
// interface ID the requester sends to.
type LinkReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// local_addr is the acceptor's link local underlay address, "host:port".
	LocalAddr string `protobuf:"bytes,1,opt,name=local_addr,json=localAddr,proto3" json:"local_addr,omitempty"`
	// if_id is the acceptor's interface ID of the link.
	IfId          uint32 `protobuf:"varint,2,opt,name=if_id,json=ifId,proto3" json:"if_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkReply) Reset() {
	*x = LinkReply{}
	mi := &file_proto_node_v1_link_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkReply) ProtoMessage() {}

func (x *LinkReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_v1_link_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkReply.ProtoReflect.Descriptor instead.
func (*LinkReply) Descriptor() ([]byte, []int) {
	return file_proto_node_v1_link_proto_rawDescGZIP(), []int{1}
}

func (x *LinkReply) GetLocalAddr() string {
	if x != nil {
		return x.LocalAddr
	}
	return ""
}

func (x *LinkReply) GetIfId() uint32 {
	if x != nil {
		return x.IfId
	}
	return 0
}

var File_proto_node_v1_link_proto protoreflect.FileDescriptor

const file_proto_node_v1_link_proto_rawDesc = "" +
	"\n" +
	"\x18proto/node/v1/link.proto\x12\anode.v1\"A\n" +
	"\vLinkRequest\x12\x1d\n" +
	"\n" +
	"local_addr\x18\x01 \x01(\tR\tlocalAddr\x12\x13\n" +
	"\x05if_id\x18\x02 \x01(\rR\x04ifId\"?\n" +
	"\tLinkReply\x12\x1d\n" +
	"\n" +
	"local_addr\x18\x01 \x01(\tR\tlocalAddr\x12\x13\n" +
	"\x05if_id\x18\x02 \x01(\rR\x04ifId2B\n" +
	"\vLinkService\x123\n" +
	"\aRequest\x12\x14.node.v1.LinkRequest\x1a\x12.node.v1.LinkReplyB.Z,github.com/fancl20/cion/proto/node/v1;nodev1b\x06proto3"

var (
	file_proto_node_v1_link_proto_rawDescOnce sync.Once
	file_proto_node_v1_link_proto_rawDescData []byte
)

func file_proto_node_v1_link_proto_rawDescGZIP() []byte {
	file_proto_node_v1_link_proto_rawDescOnce.Do(func() {
		file_proto_node_v1_link_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_node_v1_link_proto_rawDesc), len(file_proto_node_v1_link_proto_rawDesc)))
	})
	return file_proto_node_v1_link_proto_rawDescData
}

var file_proto_node_v1_link_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_node_v1_link_proto_goTypes = []any{
	(*LinkRequest)(nil), // 0: node.v1.LinkRequest
	(*LinkReply)(nil),   // 1: node.v1.LinkReply
}
var file_proto_node_v1_link_proto_depIdxs = []int32{
	0, // 0: node.v1.LinkService.Request:input_type -> node.v1.LinkRequest
	1, // 1: node.v1.LinkService.Request:output_type -> node.v1.LinkReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_node_v1_link_proto_init() }
func file_proto_node_v1_link_proto_init() {
	if File_proto_node_v1_link_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_node_v1_link_proto_rawDesc), len(file_proto_node_v1_link_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_node_v1_link_proto_goTypes,
		DependencyIndexes: file_proto_node_v1_link_proto_depIdxs,
		MessageInfos:      file_proto_node_v1_link_proto_msgTypes,
	}.Build()
	File_proto_node_v1_link_proto = out.File
	file_proto_node_v1_link_proto_goTypes = nil
	file_proto_node_v1_link_proto_depIdxs = nil
}
