// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/gateway/v1/directory.proto

package gatewayv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Entry is one gateway's publication: everything another node needs to
// establish a mesh tunnel to it.
type Entry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// isd_as is the publisher's ISD-AS. The directory records the ISD-AS the
	// authenticated publisher's certificate names, never the claimed one.
	IsdAs uint64 `protobuf:"varint,1,opt,name=isd_as,json=isdAs,proto3" json:"isd_as,omitempty"`
	// public_key is the node's 32-byte WireGuard public key.
	PublicKey []byte `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	// overlay_subnet is the node's overlay subnet, e.g. "10.64.1.0/24".
	OverlaySubnet string `protobuf:"bytes,3,opt,name=overlay_subnet,json=overlaySubnet,proto3" json:"overlay_subnet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_proto_gateway_v1_directory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_v1_directory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_proto_gateway_v1_directory_proto_rawDescGZIP(), []int{0}
}

func (x *Entry) GetIsdAs() uint64 {
	if x != nil {
		return x.IsdAs
	}
	return 0
}

func (x *Entry) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *Entry) GetOverlaySubnet() string {
	if x != nil {
		return x.OverlaySubnet
	}
	return ""
}

type PublishRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// entry is the publisher's claimed entry; the ISD-AS comes from the
	// authenticated certificate chain, the rest from the entry.
	Entry         *Entry `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishRequest) Reset() {
	*x = PublishRequest{}
	mi := &file_proto_gateway_v1_directory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRequest) ProtoMessage() {}

func (x *PublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_v1_directory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRequest.ProtoReflect.Descriptor instead.
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return file_proto_gateway_v1_directory_proto_rawDescGZIP(), []int{1}
}

func (x *PublishRequest) GetEntry() *Entry {
	if x != nil {
		return x.Entry
	}
	return nil
}

type PublishResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishResponse) Reset() {
	*x = PublishResponse{}
	mi := &file_proto_gateway_v1_directory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishResponse) ProtoMessage() {}

func (x *PublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_v1_directory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishResponse.ProtoReflect.Descriptor instead.
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return file_proto_gateway_v1_directory_proto_rawDescGZIP(), []int{2}
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_proto_gateway_v1_directory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_v1_directory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_proto_gateway_v1_directory_proto_rawDescGZIP(), []int{3}
}

type ListResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// entries holds one entry per publishing gateway.
	Entries       []*Entry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_proto_gateway_v1_directory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_v1_directory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_proto_gateway_v1_directory_proto_rawDescGZIP(), []int{4}
}

func (x *ListResponse) GetEntries() []*Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_proto_gateway_v1_directory_proto protoreflect.FileDescriptor

const file_proto_gateway_v1_directory_proto_rawDesc = "" +
	"\n" +
	" proto/gateway/v1/directory.proto\x12\n" +
	"gateway.v1\"d\n" +
	"\x05Entry\x12\x15\n" +
	"\x06isd_as\x18\x01 \x01(\x04R\x05isdAs\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\fR\tpublicKey\x12%\n" +
	"\x0eoverlay_subnet\x18\x03 \x01(\tR\roverlaySubnet\"9\n" +
	"\x0ePublishRequest\x12'\n" +
	"\x05entry\x18\x01 \x01(\v2\x11.gateway.v1.EntryR\x05entry\"\x11\n" +
	"\x0fPublishResponse\"\r\n" +
	"\vListRequest\";\n" +
	"\fListResponse\x12+\n" +
	"\aentries\x18\x01 \x03(\v2\x11.gateway.v1.EntryR\aentries2\x91\x01\n" +
	"\x10DirectoryService\x12B\n" +
	"\aPublish\x12\x1a.gateway.v1.PublishRequest\x1a\x1b.gateway.v1.PublishResponse\x129\n" +
	"\x04List\x12\x17.gateway.v1.ListRequest\x1a\x18.gateway.v1.ListResponseB4Z2github.com/fancl20/cion/proto/gateway/v1;gatewayv1b\x06proto3"

var (
	file_proto_gateway_v1_directory_proto_rawDescOnce sync.Once
	file_proto_gateway_v1_directory_proto_rawDescData []byte
)

func file_proto_gateway_v1_directory_proto_rawDescGZIP() []byte {
	file_proto_gateway_v1_directory_proto_rawDescOnce.Do(func() {
		file_proto_gateway_v1_directory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_gateway_v1_directory_proto_rawDesc), len(file_proto_gateway_v1_directory_proto_rawDesc)))
	})
	return file_proto_gateway_v1_directory_proto_rawDescData
}

var file_proto_gateway_v1_directory_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_gateway_v1_directory_proto_goTypes = []any{
	(*Entry)(nil),           // 0: gateway.v1.Entry
	(*PublishRequest)(nil),  // 1: gateway.v1.PublishRequest
	(*PublishResponse)(nil), // 2: gateway.v1.PublishResponse
	(*ListRequest)(nil),     // 3: gateway.v1.ListRequest
	(*ListResponse)(nil),    // 4: gateway.v1.ListResponse
}
var file_proto_gateway_v1_directory_proto_depIdxs = []int32{
	0, // 0: gateway.v1.PublishRequest.entry:type_name -> gateway.v1.Entry
	0, // 1: gateway.v1.ListResponse.entries:type_name -> gateway.v1.Entry
	1, // 2: gateway.v1.DirectoryService.Publish:input_type -> gateway.v1.PublishRequest
	3, // 3: gateway.v1.DirectoryService.List:input_type -> gateway.v1.ListRequest
	2, // 4: gateway.v1.DirectoryService.Publish:output_type -> gateway.v1.PublishResponse
	4, // 5: gateway.v1.DirectoryService.List:output_type -> gateway.v1.ListResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_gateway_v1_directory_proto_init() }
func file_proto_gateway_v1_directory_proto_init() {
	if File_proto_gateway_v1_directory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_gateway_v1_directory_proto_rawDesc), len(file_proto_gateway_v1_directory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_gateway_v1_directory_proto_goTypes,
		DependencyIndexes: file_proto_gateway_v1_directory_proto_depIdxs,
		MessageInfos:      file_proto_gateway_v1_directory_proto_msgTypes,
	}.Build()
	File_proto_gateway_v1_directory_proto = out.File
	file_proto_gateway_v1_directory_proto_goTypes = nil
	file_proto_gateway_v1_directory_proto_depIdxs = nil
}
